### ISSUE TITLE
Game crashing (cancelled)

### ISSUE THREAD

**Issue by LePoke** [Geometrically/PrehistoricEclipse#10]
Basicly, when i install the mod on the game, i cant play it, because forge loads it and the crash report window appears closing the game.

this happens with the last version of the mod.

[crash-2019-01-15_22.02.53-client.txt](https://github.com/Geometrically/PrehistoricEclipse/files/2762492/crash-2019-01-15_22.02.53-client.txt)

Thanks for reading.

Update 1: I investigated and find that this mod needs other mods to working, sorry for my error.

**Comment by Geometrically** [comment]
Alright.
