### ISSUE TITLE
Animals sea

### ISSUE THREAD

**Issue by Conquerorelmas** [Geometrically/PrehistoricEclipse#4]
Plesiosaurus, Dunkleosteus, Sea Scorpion and Saurichtys can't spawn with the eggs with at least the latest version.

**Comment by Geometrically** [comment]
Thanks for the report! It will be fixed in the next version.

**Comment by Geometrically** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Water Animals spawn on land in the dimension](https://trello.com/c/wCAvEget/30-water-animals-spawn-on-land-in-the-dimension)
