### ISSUE TITLE
Tupandactylus flying anim broken

### ISSUE THREAD

**Issue by prohitman** [Geometrically/PrehistoricEclipse#6]
Tupandactylus after flying a while flies while with sitting animation 
![2018-09-27_13 34 01](https://user-images.githubusercontent.com/43189387/46586721-41967380-ca7a-11e8-8489-c03e4edfa405.png)

**Comment by Geometrically** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Tupandactylus sometimes stops playing the fly animation while in the air](https://trello.com/c/ndr7jMxN/56-tupandactylus-sometimes-stops-playing-the-fly-animation-while-in-the-air)
