### ISSUE TITLE
T-Rex Run anim replaces Idle anim

### ISSUE THREAD

**Issue by enzo7098631** [Geometrically/PrehistoricEclipse#7]
![screenshot 245](https://user-images.githubusercontent.com/44329916/47261916-d13f1780-d4a7-11e8-8933-1c6146f0f842.png)
the t-rex run animation is playing instead of idle. i must've broke the mod somehow, because it usually doesn't do this. it WAS using idle anim, but out of nowhere it became the run anim.

**Comment by Geometrically** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Run animation plays when an entity is not moving](https://trello.com/c/vIc0UyFJ/59-run-animation-plays-when-an-entity-is-not-moving)

**Comment by Geometrically** [comment]
Fixed!
